import {homedir} from 'node:os';
import assert from 'node:assert/strict';import{spawn,execFileSync}from'node:child_process';import{createServer}from'node:http';import{createInterface}from'node:readline';import{mkdirSync,writeFileSync,readFileSync,openSync}from'node:fs';import{join,resolve}from'node:path';
const area=join(process.env.GHOSTLIGHT_LINUX_AREA,'npm'),launcher=join(area,'prefix/bin/ghostlight'),env={...process.env,GHOSTLIGHT_HOME:join(area,'cache')};for(const[key,folder]of Object.entries({XDG_CONFIG_HOME:'config',XDG_CACHE_HOME:'cache',XDG_DATA_HOME:'data',XDG_STATE_HOME:'state'})){env[key]=join(area,folder);mkdirSync(env[key],{recursive:true})}mkdirSync(join(area,'home'),{recursive:true});
execFileSync('bwrap',['--bind','/','/','--bind',join(area,'home'),homedir(),'--',launcher,'install','--all-browsers','--no-clients','--no-open'],{env,stdio:'pipe'});
const browser=spawn(process.env.GHOSTLIGHT_LINUX_CHROMIUM,['--no-first-run','--no-default-browser-check','--disable-background-networking','--disable-component-update','--remote-debugging-port=0','--load-extension='+process.env.GHOSTLIGHT_LINUX_EXTENSION,'about:blank'],{env,detached:true,stdio:['ignore',openSync(join(area,'browser.log'),'a'),openSync(join(area,'browser.log'),'a')]});browser.unref();
const report={release_ready:false,version:process.env.GHOSTLIGHT_LINUX_PREVIOUS_VERSION,adapter:JSON.parse(readFileSync(join(process.env.GHOSTLIGHT_LINUX_EXTENSION,'manifest.json'))).version+' source',passed:false,checks:[],browser_pid:browser.pid};writeFileSync(join(area,'context.json'),JSON.stringify({bin:join(area,'cache/bin/v'+process.env.GHOSTLIGHT_LINUX_PREVIOUS_VERSION),env:Object.fromEntries(Object.entries(env).filter(([key])=>key.startsWith('XDG_')||key==='GHOSTLIGHT_HOME')),browser_pid:browser.pid},null,2));
const delay=ms=>new Promise(r=>setTimeout(r,ms));const c=spawn(launcher,[],{env,stdio:['pipe','pipe','pipe']});let id=0;const pending=new Map();c.stderr.on('data',()=>{});createInterface({input:c.stdout}).on('line',line=>{const r=JSON.parse(line),p=pending.get(r.id);if(p){clearTimeout(p.timer);pending.delete(r.id);p.resolve(r)}});const request=(method,params={})=>new Promise((resolve,reject)=>{const n=++id,timer=setTimeout(()=>reject(new Error('MCP timeout '+method)),30000);pending.set(n,{resolve,timer});c.stdin.write(JSON.stringify({jsonrpc:'2.0',id:n,method,params})+'\n')});
const fixture=createServer((req,res)=>res.end('<h1>Public npm native delivery</h1>'));await new Promise(r=>fixture.listen(0,'127.0.0.1',r));
try{const init=await request('initialize',{protocolVersion:'2025-11-25',capabilities:{},clientInfo:{name:'npm route acceptance',version:'1'}});assert.equal(init.result.serverInfo.version,process.env.GHOSTLIGHT_LINUX_PREVIOUS_VERSION);c.stdin.write('{"jsonrpc":"2.0","method":"notifications/initialized"}\n');const deadline=Date.now()+30000;let ready=false;while(Date.now()<deadline){const d=JSON.parse(execFileSync(join(area,'cache/bin/v'+process.env.GHOSTLIGHT_LINUX_PREVIOUS_VERSION+'/ghostlight'),['doctor','--json'],{env,encoding:'utf8'}));if(d.readiness.state==='ready'){ready=true;break}await delay(100)}assert.ok(ready);report.checks.push('npm-generated-bin-initializes-public-MCP-and-native-browser');const call=async(name,args)=>{const r=await request('tools/call',{name,arguments:args});assert.equal(r.result?.structuredContent?.status,'succeeded',JSON.stringify(r));return r.result};const opened=await call('browser_navigate',{url:'http://localhost:'+fixture.address().port,new_tab:true});const tab=opened.structuredContent.facts.tab;await call('browser_wait',{tab,condition:'load_ready'});const read=await call('browser_read',{tab});assert.match(read.structuredContent.facts.text,/Public npm native delivery/);const capture=await call('browser_screenshot',{tab});assert.ok(capture.content.some(x=>x.type==='image'));report.checks.push('native-installed-open-read-and-image-receipt');report.passed=true;console.log(report)}catch(error){report.failure=error.message;console.error(error);process.exitCode=1}finally{c.stdin.end();fixture.closeAllConnections();fixture.close();writeFileSync(join(area,'native.json'),JSON.stringify(report,null,2)+'\n')}
