//! Stable transport-only negotiation between the browser relay and the local service.

use serde::{Deserialize, Serialize};

/// Browser relay protocol major understood by this build.
pub const BROWSER_RELAY_MAJOR: u16 = 1;

/// Opening request sent by the native host before any opaque adapter frame.
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case", deny_unknown_fields)]
pub enum BrowserRelayRequest {
    /// Authenticate one browser relay connection.
    Hello {
        /// Relay protocol major offered by the native host.
        major: u16,
        /// Random runtime token published by the current service.
        token: String,
    },
}

/// Opening response returned before the service reads opaque adapter frames.
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case", deny_unknown_fields)]
pub enum BrowserRelayResponse {
    /// The local relay connection is authenticated and compatible.
    Accepted {
        /// Relay protocol major selected by the service.
        major: u16,
    },
    /// The service rejected the local relay connection.
    Rejected {
        /// Stable transport-only failure code.
        code: String,
        /// Bounded local diagnostic.
        message: String,
    },
}

/// Native-port lifecycle notice generated by the relay, not the orchestrator.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case", deny_unknown_fields)]
pub enum BrowserRelayStatus {
    /// The native host is still alive but the local service is unavailable.
    BackendUnavailable,
}

#[cfg(test)]
mod tests {
    use super::{
        BrowserRelayRequest, BrowserRelayResponse, BrowserRelayStatus, BROWSER_RELAY_MAJOR,
    };

    #[test]
    fn relay_messages_round_trip() {
        let request = BrowserRelayRequest::Hello {
            major: BROWSER_RELAY_MAJOR,
            token: "runtime_test".into(),
        };
        let response = BrowserRelayResponse::Accepted {
            major: BROWSER_RELAY_MAJOR,
        };
        let status = BrowserRelayStatus::BackendUnavailable;
        assert_eq!(
            serde_json::from_slice::<BrowserRelayRequest>(&serde_json::to_vec(&request).unwrap())
                .unwrap(),
            request
        );
        assert_eq!(
            serde_json::from_slice::<BrowserRelayResponse>(&serde_json::to_vec(&response).unwrap())
                .unwrap(),
            response
        );
        assert_eq!(
            serde_json::from_slice::<BrowserRelayStatus>(&serde_json::to_vec(&status).unwrap())
                .unwrap(),
            status
        );
    }
}
