import {homedir} from 'node:os';
import assert from 'node:assert/strict';import{spawn,execFileSync}from'node:child_process';import{readFileSync,writeFileSync,mkdirSync,existsSync,openSync}from'node:fs';import{join,resolve}from'node:path';import{createServer}from'node:http';import{cdp,mcp,until,delay}from'./lib.mjs';
const area=join(process.env.GHOSTLIGHT_LINUX_AREA,'cold-'+Date.now());mkdirSync(area,{recursive:true});const report={release_ready:false,passed:false,phases:[]};let browser,dev,client;
const server=createServer((req,res)=>res.end('<h1>Cold connection accepted</h1>'));await new Promise(done=>server.listen(0,'127.0.0.1',done));
try{for(const state of ['awake','stopped']){const dir=join(area,state),bin=join(dir,'bin'),env={...process.env};mkdirSync(bin,{recursive:true});mkdirSync(join(dir,'home'));execFileSync('tar',['-xzf',process.env.GHOSTLIGHT_LINUX_PORTABLE_ARCHIVE,'-C',bin,'--strip-components=1']);for(const[key,name]of Object.entries({XDG_CONFIG_HOME:'config',XDG_CACHE_HOME:'cache',XDG_DATA_HOME:'data',XDG_STATE_HOME:'state'})){env[key]=join(dir,name);mkdirSync(env[key])}
 browser=spawn(process.env.GHOSTLIGHT_LINUX_CHROMIUM,['--no-first-run','--no-default-browser-check','--disable-background-networking','--disable-component-update','--remote-debugging-port=0','--load-extension='+process.env.GHOSTLIGHT_LINUX_EXTENSION,'about:blank'],{env,detached:true,stdio:['ignore',openSync(join(dir,'browser.log'),'a'),openSync(join(dir,'browser.log'),'a')]});browser.unref();
 const portFile=join(env.XDG_CONFIG_HOME,'chromium/DevToolsActivePort');await until(()=>existsSync(portFile),'fresh dedicated browser');dev=await cdp(portFile);let targets=await dev.send('Target.getTargets');const worker=await until(async()=>(await dev.send('Target.getTargets')).targetInfos.find(t=>t.type==='service_worker'&&t.url.endsWith('/service-worker.js')),'unpacked adapter');const evaluate=await dev.attach(worker.targetId);await until(()=>evaluate("typeof uiSnapshot==='function' && uiSnapshot().link_state==='host_absent'"),'observed initial host absence');const before=await evaluate('({link_state:uiSnapshot().link_state,connected:uiSnapshot().connected})');assert.equal(existsSync(join(env.XDG_CONFIG_HOME,'chromium/NativeMessagingHosts/org.sylin.ghostlight.json')),false);
 if(state==='stopped'){await dev.send('Target.detachFromTarget',{targetId:worker.targetId});const versions=new Map();dev.ws.addEventListener('message',({data})=>{const m=JSON.parse(data);if(m.method==='ServiceWorker.workerVersionUpdated')for(const v of m.params.versions)versions.set(v.versionId,v)});const page=(await dev.send('Target.getTargets')).targetInfos.find(t=>t.type==='page');const {sessionId}=await dev.send('Target.attachToTarget',{targetId:page.targetId,flatten:true});await dev.send('ServiceWorker.enable',{},sessionId);const version=await until(()=>[...versions.values()].find(v=>v.scriptURL===worker.url&&v.runningStatus==='running'),'worker version');await dev.send('ServiceWorker.stopWorker',{versionId:version.versionId},sessionId);await until(()=>versions.get(version.versionId)?.runningStatus==='stopped','observed stopped worker');}
 const started=Date.now();const output=execFileSync('bwrap',['--bind','/','/','--bind',join(dir,'home'),homedir(),'--',join(bin,'ghostlight'),'install','--all-browsers','--no-clients','--no-open'],{env,encoding:'utf8',timeout:30000});writeFileSync(join(dir,'install.log'),output);
 await until(()=>JSON.parse(execFileSync(join(bin,'ghostlight'),['doctor','--json'],{env,encoding:'utf8',timeout:10000})).readiness?.state==='ready','automatic connection after install',45000);const connectedMs=Date.now()-started;const info=await dev.send('SystemInfo.getProcessInfo');assert.ok(info.processInfo.some(p=>p.type==='browser'&&p.id===browser.pid));client=await mcp('Cold extension-first '+state,join(bin,'ghostlight-mcp-connector'),env);const opened=await client.call('browser_navigate',{url:'http://localhost:'+server.address().port,new_tab:true});assert.equal(opened.structuredContent.status,'succeeded',JSON.stringify(opened.structuredContent));const read=await client.call('browser_read',{tab:opened.structuredContent.facts.tab});assert.equal(read.structuredContent.status,'succeeded');assert.match(read.structuredContent.facts.text,/Cold connection accepted/);report.phases.push({name:'extension-first-'+state,status:'passed',before,browser_pid:browser.pid,connected_ms:connectedMs,first_task_ms:Date.now()-started});console.log('PASS extension-first',state,connectedMs);client.close();client=null;await dev.send('Browser.close');dev.close();dev=null;await until(()=>!existsSync('/proc/'+browser.pid),'dedicated browser exit');browser=null;writeFileSync(join(dir,'context.json'),JSON.stringify({bin,env:Object.fromEntries(Object.entries(env).filter(([k])=>k.startsWith('XDG_')))},null,2));}
 report.passed=true;
}catch(error){report.failure=error.message;console.error(error);process.exitCode=1}finally{client?.close();if(dev){try{await dev.send('Browser.close')}catch{}dev.close()}server.closeAllConnections();server.close();writeFileSync(join(area,'results.json'),JSON.stringify(report,null,2)+'\n');console.log(area)}
