import assert from 'node:assert/strict';
import {spawn,execFileSync} from 'node:child_process';
import {readFileSync,existsSync} from 'node:fs';
import {resolve,join} from 'node:path';
import {createInterface} from 'node:readline';
export const area=resolve(process.env.GHOSTLIGHT_LINUX_AREA),context=existsSync(join(area,'context.json'))?JSON.parse(readFileSync(join(area,'context.json'))):{bin:process.env.GHOSTLIGHT_LINUX_BIN_DIR,env:{}},bin=context.bin,env={...process.env,...context.env};
export const delay=ms=>new Promise(r=>setTimeout(r,ms));
export async function until(fn,label,timeout=30000){const end=Date.now()+timeout;do{const v=await fn();if(v)return v;await delay(100)}while(Date.now()<end);throw new Error('Timeout: '+label)}
export function product(args){return execFileSync(join(bin,'ghostlight'),args,{env,encoding:'utf8',timeout:15000})}
export const doctor=()=>JSON.parse(product(['doctor','--json']));
function channel(write){let id=0;const pending=new Map();return {send(method,params={},sessionId){return new Promise((done,reject)=>{const n=++id;const timer=setTimeout(()=>{pending.delete(n);reject(new Error('Timeout: '+method))},45000);pending.set(n,{done,reject,timer});write({id:n,method,params,...(sessionId?{sessionId}:{})})})},receive(msg){const p=pending.get(msg.id);if(p){pending.delete(msg.id);clearTimeout(p.timer);msg.error?p.reject(new Error(JSON.stringify(msg.error))):p.done(msg.result)}},close(){for(const p of pending.values()){clearTimeout(p.timer);p.reject(new Error('Transport closed'))}pending.clear()}}}
export async function mcp(label='Linux local governance',mcpImage=join(bin,'ghostlight-mcp-connector'),mcpEnvironment=env,mcpArguments=[]) {const child=spawn(mcpImage,mcpArguments,{env:mcpEnvironment,stdio:['pipe','pipe','pipe']});child.stderr.on('data',()=>{});const c=channel(msg=>child.stdin.write(JSON.stringify({jsonrpc:'2.0',...msg})+'\n'));createInterface({input:child.stdout}).on('line',line=>c.receive(JSON.parse(line)));child.on('exit',()=>c.close());try{await c.send('initialize',{protocolVersion:'2025-11-25',capabilities:{},clientInfo:{name:label,version:'1'}})}catch(error){child.stdin.end();throw error};child.stdin.write('{"jsonrpc":"2.0","method":"notifications/initialized"}\n');return {...c,child,call:async(name,args={})=>c.send('tools/call',{name,arguments:args}),close(){child.stdin.end()}}}
export async function cdp(file=join(env.XDG_CONFIG_HOME,'chromium/DevToolsActivePort')){const [port,path]=readFileSync(file,'utf8').trim().split(/\r?\n/);const ws=new WebSocket(`ws://127.0.0.1:${port}${path}`);await new Promise((done,reject)=>{ws.onopen=done;ws.onerror=reject});const c=channel(msg=>ws.send(JSON.stringify(msg)));ws.onmessage=({data})=>c.receive(JSON.parse(data));return {...c,ws,async attach(target){const {sessionId}=await c.send('Target.attachToTarget',{targetId:target,flatten:true});return async expression=>{const r=await c.send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true},sessionId);assert.equal(r.exceptionDetails,undefined,JSON.stringify(r.exceptionDetails));return r.result.value}},close(){ws.close()}}}
