import assert from 'node:assert/strict';import{spawn}from'node:child_process';import{createServer}from'node:http';import{readFileSync,writeFileSync,mkdirSync,openSync,readlinkSync,existsSync,unlinkSync}from'node:fs';import{join,resolve}from'node:path';import{area,bin,env,mcp,cdp,delay,until}from'./lib.mjs';
const out=join(area,'plural-'+Date.now());mkdirSync(out);const report={passed:false,release_ready:false,phases:[]};const save=()=>writeFileSync(join(out,'results.json'),JSON.stringify(report,null,2)+'\n');let phase='preflight';const clients=[],devs=[];const pass=facts=>{report.phases.push({name:phase,status:'passed',...facts});save();console.log('PASS',phase)};
assert.ok(env.XDG_STATE_HOME?.startsWith(area+'/context/'),'Run acceptance/start.mjs for this dedicated area first');
const policy=join(env.XDG_STATE_HOME,'ghostlight/user-policy.json');if(existsSync(policy))unlinkSync(policy);
const server=createServer((req,res)=>{res.setHeader('content-type','text/html');res.end('<title>Plural browser fixture</title><h1>Browser continuity</h1><label>Draft<input aria-label="Draft"></label>')});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://localhost:'+server.address().port;
async function call(c,n,a={},expected='succeeded'){const reply=await c.call(n,a);assert.equal(reply.structuredContent.status,expected,JSON.stringify(reply.structuredContent));return reply.structuredContent}
async function connect(file){const d=await cdp(file);devs.push(d);return d}
async function page(d,url){const t=await until(async()=>(await d.send('Target.getTargets')).targetInfos.find(x=>x.url===url),'own document');return d.attach(t.targetId)}
function launch(image,extra=[]){const child=spawn(image,['--no-first-run','--no-default-browser-check','--disable-background-networking','--disable-component-update','--remote-debugging-port=0','--load-extension='+process.env.GHOSTLIGHT_LINUX_EXTENSION,...extra],{env,detached:true,stdio:['ignore',openSync(join(out,'browser.log'),'a'),openSync(join(out,'browser.log'),'a')]});child.unref();return child.pid}
try{
 const discovery=await mcp('Plural inventory');clients.push(discovery);let inventory=await until(async()=>{const list=(await call(discovery,'browser_tabs',{action:'list'})).facts.browsers;return list.some(x=>x.name==='Brave')&&list.some(x=>x.name==='Chromium')&&list},'initial connected browser pair');const brave=inventory.find(x=>x.name==='Brave'),chromium=inventory.find(x=>x.name==='Chromium');assert.ok(brave&&chromium);
 const chromiumDev=await connect();let braveDev=await connect(join(env.XDG_CONFIG_HOME,'BraveSoftware/Brave-Browser/DevToolsActivePort'));
 const records=[];
 for(const [browser,dev,label]of [[chromium,chromiumDev,'Chromium'],[brave,braveDev,'Brave']]){const c=await mcp('Installed '+label);clients.push(c);const url=base+'/'+label;const opened=await call(c,'browser_navigate',{url,new_tab:true,browser:browser.browser});await call(c,'browser_wait',{tab:opened.facts.tab,condition:'load_ready'});await call(c,'browser_fill_form',{tab:opened.facts.tab,fields:[{selector:{name:'Draft'},value:label+' retained draft'}]});const raw=await page(dev,url);assert.equal(await raw("document.querySelector('input').value"),label+' retained draft');records.push({c,dev,label,browser:browser.browser,tab:opened.facts.tab,url,raw});}
 phase='two-supported-families-retain-separate-drafts-and-workspaces';for(const record of records){const tabs=await call(record.c,'browser_tabs',{action:'list'});assert.equal(tabs.facts.tabs.length,1);assert.equal(tabs.facts.tabs[0].tab,record.tab)}pass({browsers:records.map(({label,browser})=>({label,browser}))});
 phase='second-Chromium-profile-is-an-independent-adapter';const profilePid=launch(process.env.GHOSTLIGHT_LINUX_CHROMIUM,['--profile-directory=Profile 1','about:blank']);const second=chromiumDev;
 inventory=await until(async()=>{const list=(await call(discovery,'browser_tabs',{action:'list'})).facts.browsers;return list.length===3&&list},'three real adapters');const extra=inventory.find(x=>!records.some(r=>r.browser===x.browser));const c=await mcp('Installed second profile');clients.push(c);const url=base+'/profile-two';const opened=await call(c,'browser_navigate',{url,new_tab:true,browser:extra.browser});await call(c,'browser_fill_form',{tab:opened.facts.tab,fields:[{selector:{name:'Draft'},value:'Profile two retained draft'}]});const raw=await page(second,url);assert.equal(await raw("document.querySelector('input').value"),'Profile two retained draft');records.push({c,dev:second,label:'profile-two',browser:extra.browser,tab:opened.facts.tab,url,raw});pass({profile_pid:profilePid,adapter_count:inventory.length});
 phase='moving-controlled-tab-to-another-window-keeps-ownership';let worker,workerEval;for(const candidate of (await chromiumDev.send('Target.getTargets')).targetInfos.filter(x=>x.type==='service_worker'&&x.url.endsWith('/service-worker.js'))){const evaluate=await chromiumDev.attach(candidate.targetId);if((await evaluate("chrome.storage.local.get('ghostlight.browser_id')"))['ghostlight.browser_id']===records[0].browser){worker=candidate;workerEval=evaluate;break}}assert.ok(worker,'Exact profile worker required');const physical=await workerEval(`(async()=>{const tab=(await chrome.tabs.query({})).find(t=>t.url===${JSON.stringify(records[0].url)});const before=tab.windowId;const moved=await chrome.windows.create({tabId:tab.id});return {tab:tab.id,before,after:moved.id}})()`);assert.notEqual(physical.before,physical.after);await call(records[0].c,'browser_read',{tab:records[0].tab});assert.equal(await records[0].raw("document.querySelector('input').value"),'Chromium retained draft');pass({physical});
 phase='extension-reload-keeps-drafts-and-restores-fresh-work';const workerId=worker.targetId;workerEval('chrome.runtime.reload()').catch(()=>{});await until(async()=>(await chromiumDev.send('Target.getTargets')).targetInfos.some(x=>x.type==='service_worker'&&x.url===worker.url&&x.browserContextId===worker.browserContextId&&x.targetId!==workerId),'reloaded worker');assert.equal(await records[0].raw("document.querySelector('input').value"),'Chromium retained draft');const newWorker=(await chromiumDev.send('Target.getTargets')).targetInfos.find(x=>x.type==='service_worker'&&x.browserContextId===worker.browserContextId&&x.url===worker.url);const newWorkerEval=await chromiumDev.attach(newWorker.targetId);await until(()=>newWorkerEval("typeof uiSnapshot === 'function' && uiSnapshot().connected && uiSnapshot().compatible"),'native reconnect after reload');const fresh=await call(records[0].c,'browser_navigate',{url:base+'/after-reload',new_tab:true});await call(records[0].c,'browser_read',{tab:fresh.facts.tab});pass({draft_retained:true});
 phase='absent-bound-browser-never-switches-profiles';const prior=JSON.parse(readFileSync(join(area,'brave.json'))).pid;const expectedImage=process.env.GHOSTLIGHT_LINUX_BRAVE;assert.equal(readlinkSync('/proc/'+prior+'/exe'),expectedImage);const info=await braveDev.send('SystemInfo.getProcessInfo');assert.ok(info.processInfo.some(x=>x.type==='browser'&&x.id===prior));await braveDev.send('Browser.close');braveDev.close();await until(()=>!existsSync('/proc/'+prior),'dedicated Brave exit');
 const missing=await call(records[1].c,'browser_read',{tab:records[1].tab},'failed');assert.equal(missing.facts.reason,'tab_unavailable');const pinned=await call(records[1].c,'browser_tabs',{action:'list'},'failed');assert.equal(pinned.facts.reason,'browser_wrong_profile');assert.equal(missing.effect,'none');for(const record of [records[0],records[2]]){assert.equal(await record.raw("document.querySelector('input').value"),record.label==='Chromium'?'Chromium retained draft':'Profile two retained draft');await call(record.c,'browser_tabs',{action:'list'})}pass();
 phase='browser-restart-retains-adapter-identity-and-MCP-connection';const restartedPid=launch(expectedImage,['--restore-last-session']);writeFileSync(join(area,'brave.json'),JSON.stringify({pid:restartedPid}));await until(async()=>{try{const d=await cdp(join(env.XDG_CONFIG_HOME,'BraveSoftware/Brave-Browser/DevToolsActivePort'));const info=await d.send('SystemInfo.getProcessInfo');if(info.processInfo.some(x=>x.type==='browser'&&x.id===restartedPid)){braveDev=d;devs.push(d);return true}d.close()}catch{}},'restarted Brave control');await until(async()=>(await call(discovery,'browser_tabs',{action:'list'})).facts.browsers.some(x=>x.browser===brave.browser),'same stable Brave adapter');const next=await call(records[1].c,'browser_navigate',{url:base+'/after-restart',new_tab:true});await call(records[1].c,'browser_read',{tab:next.facts.tab});pass({previous_pid:prior,restarted_pid:restartedPid,browser:brave.browser});
 report.passed=true;
}catch(error){report.phases.push({name:phase,status:'failed',reason:error.message});console.error(error);process.exitCode=1}finally{for(const c of clients)c.close();for(const d of devs)d.close();server.closeAllConnections();server.close();save();console.log(out)}
