import {homedir} from 'node:os';
import{connect}from'node:net';
import assert from 'node:assert/strict';import{spawn,execFileSync}from'node:child_process';import{createServer}from'node:http';import{readFileSync,writeFileSync,mkdirSync,existsSync,openSync,readdirSync,readlinkSync}from'node:fs';import{join,resolve}from'node:path';import{mcp,cdp,until,delay}from'../lib.mjs';
const area=join(process.env.GHOSTLIGHT_LINUX_AREA,'managed/run-'+Date.now()),bin=join(area,'bin'),env={...process.env};mkdirSync(bin,{recursive:true});mkdirSync(join(area,'org'));mkdirSync(join(area,'home'),{recursive:true});execFileSync('tar',['-xzf',process.env.GHOSTLIGHT_LINUX_PORTABLE_ARCHIVE,'-C',bin,'--strip-components=1']);for(const[k,v]of Object.entries({XDG_CONFIG_HOME:'config',XDG_CACHE_HOME:'cache',XDG_DATA_HOME:'data',XDG_STATE_HOME:'state'})){env[k]=join(area,v);mkdirSync(env[k],{recursive:true})}
const binary=join(bin,'ghostlight'),seed=join(area,'keys/policy-ed25519.seed'),source=join(area,'org/policy.bundle');const cli=args=>execFileSync(binary,args,{env,encoding:'utf8',timeout:15000});cli(['policy','keygen',join(area,'keys'),'--ed25519-only']);const pubkey=cli(['policy','pubkey',seed]).trim().split(' ')[1];writeFileSync(join(area,'org/managed.json'),JSON.stringify({source:'policy.bundle',pubkey_ed25519:pubkey,poll_seconds:1}));writeFileSync(source,'invalid initial policy');
const wrap=['--unshare-user','--bind','/','/','--dev','/dev','--overlay-src','/etc','--tmp-overlay','/etc','--ro-bind',join(area,'org'),'/etc/ghostlight','--bind',join(area,'home'),homedir(),'--'];execFileSync('bwrap',[...wrap,binary,'install','--all-browsers','--no-clients','--no-open'],{env,stdio:'pipe'});
const browser=spawn('bwrap',[...wrap,process.env.GHOSTLIGHT_LINUX_CHROMIUM,'--no-first-run','--no-default-browser-check','--disable-background-networking','--disable-component-update','--remote-debugging-port=0','--load-extension='+process.env.GHOSTLIGHT_LINUX_EXTENSION,'about:blank'],{env,detached:true,stdio:['ignore',openSync(join(area,'browser.log'),'a'),openSync(join(area,'browser.log'),'a')]});browser.unref();
const report={passed:false,release_ready:false,phases:[]};const save=()=>writeFileSync(join(area,'results.json'),JSON.stringify(report,null,2)+'\n');let phase='preflight',dev,client;const check=()=>{report.phases.push({name:phase,status:'passed'});save();console.log('PASS',phase)};let ipRequests=0;const fixture=createServer((req,res)=>{if(req.headers.host.startsWith('127.0.0.1'))ipRequests++;res.end('<title>Managed fixture</title><h1>Signed local authority</h1>')});await new Promise(r=>fixture.listen(0,'127.0.0.1',r));const url='http://localhost:'+fixture.address().port;
async function call(name,args={},expected='succeeded'){const r=(await client.call(name,args)).structuredContent;assert.equal(r?.status,expected,JSON.stringify(r));return r}
function publish(sequence,allowed){const file=join(area,'policy-'+sequence+'.json');writeFileSync(file,JSON.stringify({schema:3,name:'Local signed acceptance',version:String(sequence),grants:[{id:'parent',hosts:{allow:['localhost']},allowed}]}));cli(['policy','sign',file,'--ed25519-seed',seed,'--sequence',String(sequence),'--out',source]);return readFileSync(source)}
async function state(sequence){return until(async()=>{try{await call('policy_explain')}catch{return false}const path=join(env.XDG_STATE_HOME,'ghostlight/managed-status.json');if(!existsSync(path))return false;const s=JSON.parse(readFileSync(path));return s.verified&&s.sequence===sequence&&s},'managed sequence '+sequence)}
try{const port=join(env.XDG_CONFIG_HOME,'chromium/DevToolsActivePort');await until(()=>existsSync(port),'managed browser');dev=await cdp(port);const worker=await until(async()=>(await dev.send('Target.getTargets')).targetInfos.find(x=>x.type==='service_worker'&&x.url.endsWith('/service-worker.js')),'managed adapter');const evaluate=await dev.attach(worker.targetId);await until(()=>evaluate("typeof uiSnapshot==='function'&&uiSnapshot().connected"),'actual native connection');let initialized=false;const connecting=mcp('Installed signed policy','bwrap',env,[...wrap,join(bin,'ghostlight-mcp-connector')]);connecting.then(value=>{client=value;initialized=true}).catch(()=>{});
 phase='invalid-managed-cold-source-fails-closed';const endpoint=JSON.parse(readFileSync(join(bin,'ghostlight-runtime.json')));const refusal=await new Promise((done,reject)=>{const socket=connect(endpoint.service_port,'127.0.0.1',()=>socket.write(JSON.stringify({kind:'hello',major:endpoint.service_bridge_major,token:endpoint.token,client_label:'Cold managed admission',channel:'mcp'})+'\n'));let data='';socket.setTimeout(5000,()=>{socket.destroy();reject(Error('Admission timeout'))});socket.on('error',reject);socket.on('data',chunk=>{data+=chunk;if(data.includes('\n')){socket.destroy();done(JSON.parse(data.split('\n')[0]))}})});assert.equal(refusal.kind,'error');assert.equal(refusal.code,'invalid_authority');await delay(500);assert.equal(initialized,false);assert.equal(ipRequests,0);check();
 phase='verified-signed-source-permits-real-browser-work';const first=publish(1,['read','action','write','execute']);client=await connecting;await state(1);const opened=await call('browser_navigate',{url,new_tab:true});let tab=opened.facts.tab;const read=await call('browser_read',{tab});assert.match(read.facts.text,/Signed local authority/);check();
 phase='managed-host-denial-has-no-HTTP-effect';const denied=await call('browser_navigate',{url:'http://127.0.0.1:'+fixture.address().port,new_tab:true},'blocked');assert.equal(denied.effect,'none');assert.equal(ipRequests,0);check();
 phase='invalid-reload-retains-last-verified-authority';writeFileSync(source,'invalid replacement');await delay(1200);await call('browser_read',{tab});const stale=await state(1);assert.notEqual(stale.freshness,'fresh');check();
 phase='restart-uses-verified-cache-with-unavailable-source';const pids=readdirSync('/proc').filter(p=>/^\d+$/.test(p)).filter(p=>{try{return readlinkSync('/proc/'+p+'/exe')===binary}catch{return false}});assert.equal(pids.length,1);process.kill(Number(pids[0]),'SIGTERM');await until(async()=>{try{const c=(await client.send('tools/list',{}));return Array.isArray(c.tools)}catch{return false}},'retained MCP negotiation');await state(1);await until(()=>evaluate("typeof uiSnapshot==='function'&&uiSnapshot().connected"),'native after authority restart');const recovered=await call('browser_navigate',{url,new_tab:true});tab=recovered.facts.tab;await call('browser_read',{tab});check();
 phase='higher-signed-sequence-tightens-existing-work';publish(2,['read']);await state(2);const restricted=await call('browser_execute',{tab,script:"document.title='must-not-run'"},'blocked');assert.equal(restricted.effect,'none');const targets=(await dev.send('Target.getTargets')).targetInfos.filter(x=>x.url===url+'/');assert.equal(targets.length,2);const raw=await Promise.all(targets.map(t=>dev.attach(t.targetId)));for(const page of raw)assert.equal(await page('document.title'),'Managed fixture');check();
 phase='signed-rollback-cannot-expand-authority';writeFileSync(source,first);await delay(1200);const rollback=await state(2);assert.notEqual(rollback.freshness,'fresh');await call('browser_execute',{tab,script:"document.title='must-not-run'"},'blocked');for(const page of raw)assert.equal(await page('document.title'),'Managed fixture');check();report.passed=true;
}catch(error){report.phases.push({name:phase,status:'failed',reason:error.message});console.error(error);process.exitCode=1}finally{client?.close();if(dev){try{await dev.send('Browser.close')}catch{}dev.close()}fixture.closeAllConnections();fixture.close();save();console.log(area)}
